### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by RDavydenko** [RDavydenko/SmartGraphQLClient#2]
- [ ] Cursor Paging
- [x] Executing raw-query
- [ ] Class generator tool using GraphQL-scheme
- [ ] Filtering by nested collections
- [x] Strings with spec-characters

**Comment by RDavydenko** [comment]
Added spec-chars escaping
https://github.com/RDavydenko/SmartGraphQLClient/pull/4

**Comment by RDavydenko** [comment]
Added raw query executing 
https://github.com/RDavydenko/SmartGraphQLClient/commit/6e1e4a92f9dea668efdc39abb9797826ecf029e2
https://github.com/RDavydenko/SmartGraphQLClient/commit/5eb47ac1bbf52bcac30cf6743e894f58a2ea41cc
https://github.com/RDavydenko/SmartGraphQLClient/commit/466edb6a6fc587b9a2252f989328693dc5bdf2ab
